apiVersion: apps/v1
kind: Deployment
metadata:
  name: subhouse
  labels:
    app: subhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subhouse
  template:
    metadata:
      name: subhouse
      labels:
        app: subhouse
    spec:
      containers:
        - name: subhouse
          image: iu_subhouse:1.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: main-port
              containerPort: 8020
              protocol: TCP
          startupProbe:
            httpGet:
              path: /healthy
              port: main-port
          livenessProbe:
            httpGet:
              port: main-port
              path: /healthy
          envFrom:
            - configMapRef:
                name: core-data
      restartPolicy: Always
      